title: "BE/Bi 103 a"
description: "Introduction to Data Analysis in the Biological Sciences"
theme: jekyll-theme-cayman

# Optional: Enable sidebar navigation
collections:
  lessons:
    output: true
    permalink: /:collection/:name

# Optional: Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Course"
    url: /course
  - title: "Lessons"
    url: /lessons
